INSERT INTO BREED (SELECT * FROM L305_karen.BREED)
go
INSERT INTO KENNEL (SELECT * FROM L305_karen.KENNEL)
go
INSERT INTO OWNER (SELECT * FROM L305_karen.OWNER)
go
INSERT INTO SHOW (SELECT * FROM L305_karen.SHOW)
go
INSERT INTO ATTENDANCE (SELECT * FROM L305_karen.ATTENDANCE)
go
INSERT INTO DOG (SELECT * FROM L305_karen.DOG)
go