SELECT BAND.NAME AS Band_Name, SONG.TITLE AS Song_Title
FROM BAND, SONG, RELEASE
WHERE BAND.BID=RELEASE.BID AND RELEASE.RID=SONG.RID
GROUP BY BAND.NAME, SONG.TITLE
HAVING count(*)>1
ORDER BY BAND.NAME
GO
