SELECT MEMBER.NAME as Guitarist_Name, Band.Name as Band_Name, Mems.STARTYEAR as Start_Year, MEMS.ENDYEAR as END_YEAR
FROM (
    SELECT BAND.BID,MEMBEROF.MID, MEMBEROF.STARTYEAR As STARTYEAR, MEMBEROF.ENDYEAR as ENDYEAR
    FROM MEMBEROF,BAND,RELEASE
    WHERE MEMBEROF.STARTYEAR>0 AND MEMBEROF.INSTRUMENT='guitar'
    AND MEMBEROF.BID=BAND.BID AND BAND.BID=RELEASE.BID
    UNION
    SELECT BAND.BID, MEMBEROF.MID, MIN(RELEASE.YEAR) AS year,MEMBEROF.ENDYEAR
    FROM BAND, RELEASE, MEMBEROF
    WHERE BAND.BID=RELEASE.BID AND MEMBEROF.INSTRUMENT='guitar' 
    AND MEMBEROF.BID = BAND.BID AND (MEMBEROF.STARTYEAR IS NULL)
    GROUP BY MEMBEROF.MID, BAND.BID,MEMBEROF.ENDYEAR) MEMS, MEMBER, BAND
WHERE MEMS.MID=MEMBER.MID AND BAND.BID=MEMS.BID
ORDER BY MEMBER.NAME, MEMS.STARTYEAR
go