select Member.Name as Guitarist_Name, Band.Name as Band_Name, Mems.STARTYEAR as Start_Year, Mems.ENDYEAR as End_Year
From Member, Band, (Select * From MemberOf where INSTRUMENT='guitar')Mems
Where Band.Bid=Mems.Bid AND Member.MID=Mems.MID
ORDER BY Member.NAME, Mems.StartYEar
go


SELECT MEMBER.NAME as Guitarist_Name, Band.Name as Band_Name, Mems.STARTYEAR as Start_Year, MEMS.ENDYEAR
FROM (
    SELECT BAND.BID,MEMBEROF.MID, MEMBEROF.STARTYEAR As STARTYEAR, MEMBEROF.ENDYEAR as ENDYEAR
    FROM MEMBEROF,BAND,RELEASE
    WHERE MEMBEROF.STARTYEAR>0 AND MEMBEROF.INSTRUMENT='guitar'
    AND MEMBEROF.BID=BAND.BID AND BAND.BID=RELEASE.BID
    UNION
    SELECT BAND.BID, MEMBEROF.MID, MIN(RELEASE.YEAR) AS year,(0)
    FROM BAND, RELEASE, MEMBEROF
    WHERE BAND.BID=RELEASE.BID AND MEMBEROF.INSTRUMENT='guitar' 
    AND MEMBEROF.BID = BAND.BID AND (MEMBEROF.STARTYEAR IS NULL)
    GROUP BY MEMBEROF.MID, BAND.BID) MEMS, MEMBER, BAND
WHERE MEMS.MID=MEMBER.MID AND BAND.BID=MEMS.BID
ORDER BY MEMBER.NAME, MEMS.STARTYEAR
go