SELECT BAND.NAME AS Band_Name, KEYS.NAME AS Keyboard_Player
FROM BAND LEFT OUTER JOIN (SELECT MEMBER.NAME,MEMBEROF.BID
    FROM MEMBEROF, MEMBER
    WHERE INSTRUMENT='keyboards' AND MEMBER.MID=MEMBEROF.MID)KEYS
ON BAND.BID=KEYS.BID
ORDER BY BAND.NAME, KEYS.NAME
go
