INSERT INTO Band (SELECT * FROM L305_karen.BAND)
go
INSERT INTO Release (SELECT * FROM L305_karen.RELEASE)
go
INSERT INTO Song (SELECT * FROM L305_karen.SONG)
go
INSERT INTO Member (SELECT * FROM L305_karen.MEMBER)
go
INSERT INTO MemberOf (SELECT * FROM L305_karen.MemberOf)
go
/**
INSERT INTO BAND VALUES(21,'TOPBAND','SCOTLAND','www.TOP.com')
go
INSERT INTO RELEASE VALUES (78, 21,'TESTALBUM','2013','ALBUM',10)
go
INSERT INTO SONG VALUES('A',78,'N')
go
INSERT INTO SONG VALUES('B',78,'N')
go
INSERT INTO SONG VALUES('C',78,'N')
go
INSERT INTO SONG VALUES('D',78,'N')
go
INSERT INTO SONG VALUES('E',78,'N')
go
INSERT INTO SONG VALUES('F',78,'N')
go
INSERT INTO SONG VALUES('G',78,'N')
go
INSERT INTO SONG VALUES('H',78,'N')
go
INSERT INTO SONG VALUES('I',78,'N')
go
INSERT INTO SONG VALUES('J',78,'N')
go
INSERT INTO SONG VALUES('K',78,'N')
go
INSERT INTO SONG VALUES('L',78,'N')
go
INSERT INTO SONG VALUES('M',78,'N')
go
INSERT INTO SONG VALUES('N',78,'N')
go
INSERT INTO SONG VALUES('O',78,'N')
go
INSERT INTO SONG VALUES('P',78,'N')
go
INSERT INTO SONG VALUES('Q',78,'N')
go
INSERT INTO SONG VALUES('R',78,'N')
go
INSERT INTO SONG VALUES('S',78,'N')
go
INSERT INTO SONG VALUES('T',78,'N')
go
INSERT INTO SONG VALUES('U',78,'N')
go
INSERT INTO SONG VALUES('V',78,'N')
go
INSERT INTO SONG VALUES('W',78,'N')
go
INSERT INTO SONG VALUES('X',78,'N')
go
*/