INSERT INTO Band (SELECT * FROM L305_karen.BAND)
go
INSERT INTO Release (SELECT * FROM L305_karen.RELEASE)
go
INSERT INTO Song (SELECT * FROM L305_karen.SONG)
go
INSERT INTO Member (SELECT * FROM L305_karen.MEMBER)
go
INSERT INTO MemberOf (SELECT * FROM L305_karen.MemberOf)
go