/*SELECT MEMBER.NAME
FROM MEMBER, (Select * from MEMBEROF, BAND where ENDYEAR IS NULL AND BAND.NAME='Iron Maiden' AND MEMBEROF.BID=BAND.BID)MO
WHERE MEMBER.MID = MO.MID
go*/


SELECT MO.NAME
FROM (SELECT * FROM MEMBEROF, MEMBER WHERE MEMBEROF.MID=MEMBER.MID)MO, (SELECT BID FROM BAND WHERE BAND.NAME='Iron Maiden')BA
WHERE MO.BID = BA.BID
go

SELECT MO.NAME
FROM (SELECT * FROM MEMBEROF, MEMBER WHERE MEMBEROF.MID=MEMBER.MID)MO
WHERE MO.BID IN (SELECT BID FROM BAND WHERE BAND.NAME='Iron Maiden')
go